name: finance_house_assessment
description: "Finance House Assessment"


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  go_router: ^16.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.7+1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  internet_connection_checker: ^3.0.1
  fluttertoast: ^8.2.12
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.10
  pretty_dio_logger: ^1.3.1
  logger: ^2.6.0
  flutter_gen_runner: ^5.11.0
  mockito: ^5.4.6
  bloc_test: ^10.0.0
  change_app_package_name: ^1.5.0

flutter_gen:
    output: lib/core/presentation/resources/
    line_length: 80 # Optional (default: 80)


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/logo/
    - assets/


